//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebOptimizationProject.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Templates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Templates() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebOptimizationProject.Resources.Templates", typeof(Templates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ### Commit {CommitNumber}
        ///
        ///Information | Value
        ///-- | --
        ///Version | {Version}
        ///Support file extension | {SupportedFileExtensions}
        ///
        ///#### Statistics
        ///
        ///Stats | Value
        ///-- | --
        ///Total optimizable files | {OptimizableFileCount}
        ///Files optimized successfully (size reduced) | {FilesOptimizedSuccessfully}
        ///Files already fully optimized | {FilesAlreadyOptimized}
        ///Files that failed to be optimized | {FilesFailedOptimization}
        ///Total size before optimization | {TotalBytesBefore}
        ///Total size after optimization | {Tot [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CommitInPullRequestMarkdownTemplate {
            get {
                return ResourceManager.GetString("CommitInPullRequestMarkdownTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Web Optimization Project optimized this repository. This commit contains the optimized files in this repository..
        /// </summary>
        internal static string CommitMarkdownTemplate {
            get {
                return ResourceManager.GetString("CommitMarkdownTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Web Optimization Project (Beta)
        ///
        ///The [Web Optimization Project](https://www.github.com/devedse/weboptimizationproject) is a project that will automatically optimizes files in git repositories by compressing them losslessly. This project was created by [Devedse](https://github.com/devedse) in an effort to save the world! :smirk:
        ///
        ///If you have any questions, feel free to create an issue or join the gitter chat:
        ///[![Join the chat at https://gitter.im/WebOptimizationProject/Lobby](https://badges.gitter.im/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PullRequestMarkdownTemplate {
            get {
                return ResourceManager.GetString("PullRequestMarkdownTemplate", resourceCulture);
            }
        }
    }
}
